sudo: false

language: cpp

matrix:
  include:
    - os: linux
      env: CONDA_PY=2.7
    - os: linux
      env: CONDA_PY=3.5
    - os: osx
      env: CONDA_PY=2.7
    - os: osx
      env: CONDA_PY=3.5

install:
  # Set the anaconda environment
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export EPICS_HOST_ARCH=darwin-x86;
      if [[ "$CONDA_PY" == "2.7" ]]; then
        curl https://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh -o miniconda.sh;
      else
        curl https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -o miniconda.sh;
      fi
    else
      export EPICS_HOST_ARCH=linux-x86_64;
      if [[ "$CONDA_PY" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q --all
  - conda install conda-build numpy swig pip anaconda-client
  # build
  - conda config --add channels paulscherrerinstitute
  - conda build conda-recipe
  - conda install pcaspy --use-local

script:
  - cd test;python gddTest.py;cd ..

after_success:
    - if [[ ! -z "$TRAVIS_TAG" ]]; then
        anaconda -t $CONDA_TOKEN upload --force $HOME/miniconda/conda-bld/${TRAVIS_OS_NAME}-64/*.tar.bz2;
        echo [distutils]                > ~/.pypirc;
        echo index-servers = mypypi    >> ~/.pypirc;
        echo [mypypi]                  >> ~/.pypirc;
        echo repository=$PYPI_URL      >> ~/.pypirc;
        echo username=$PYPI_USER       >> ~/.pypirc;
        echo password=$PYPI_PASSWORD   >> ~/.pypirc;
        export EPICS_BASE=$HOME/miniconda/epics;
        rm -f $EPICS_BASE/lib/$EPICS_HOST_ARCH/*.so*;
        rm -f $EPICS_BASE/lib/$EPICS_HOST_ARCH/*.dylib*;
        if [[ $TRAVIS_OS_NAME == "linux" && $CONDA_PY == "2.7" ]]; then
            python setup.py sdist upload -r mypypi;
        fi;
        if [[ $TRAVIS_OS_NAME == "linux" ]]; then
            python setup.py bdist_egg upload -r mypypi;
        fi;
        if [[ $TRAVIS_OS_NAME == "osx" ]]; then
            python setup.py bdist_wheel upload -r mypypi;
        fi;
      fi
